import mysql.connector as sql
conn = sql.connect(host = 'localhost', user = 'root', passwd = 'tiger',database="hotel")
c1 = conn.cursor()
c1.execute('create table restaurent(sno integer not null, itemname varchar(10), rate integer);')
c1.execute('insert into restaurent values(1,"tea",10);')
c1.execute('insert into restaurent values(2,"coffe",10);')
c1.execute('insert into restaurent values(3,"coldrink",20);')
c1.execute('insert into restaurent values(4,"samosa",10);')
c1.execute('insert into restaurent values(5,"sandwitch",50);')
c1.execute('insert into restaurent values(6,"dhokla",30);')
c1.execute('insert into restaurent values(7,"kachori",10);')
c1.execute('insert into restaurent values(8,"milk",20);')
c1.execute('insert into restaurent values(9,"noodles",50);')
c1.execute('insert into restaurent values(10,"pasta",50);')
conn.commit()
print('table created successfully')
